### ISSUE TITLE
Not Collapse after selecting the drop down name

### ISSUE THREAD

**Issue by KOSURUUDAYSAIKUMAR** [KarimEbrahemAbdelaziz/SwiftyMenu#20]
Hi, 

When I select single drop down name, It will automatically collapse (Not Expanding the cell).

Can you please me, I have a requirement.

**Comment by KarimEbrahemAbdelaziz** [comment]
@KOSURUUDAYSAIKUMAR Could you please provide a screenshot so I can help you?

**Comment by KitsuneNoctus** [comment]
@KOSURUUDAYSAIKUMAR When you created / initialized the drop down menu, what did you set the hideOptionsWhenSelect value to?
`dropDown.hideOptionsWhenSelect = true`
^The above will make it so that if it is a singleSelection menu, it will cause the menu to always collapse.

If you want it to be multi select, make sure that the `var isMultiSelect` is set to True

**Comment by KarimEbrahemAbdelaziz** [comment]
Hi @KOSURUUDAYSAIKUMAR ,

Feel free to open this issue again if you still have any questions.

Thank you.
