### ISSUE TITLE
Single Selection Menu Changing Choice

### ISSUE THREAD

**Issue by KitsuneNoctus** [KarimEbrahemAbdelaziz/SwiftyMenu#23]
Using the drop down menu and having the menu toggle so that when you make one selection, the menu closes works. The issue is if I then want to change my selection, I will tap the menu, and I see the arrow flip, but the menu does not drop down. Tap it once more and it will drop down again to allow you to make that selection again.

It is a simple thing that does not inhibit the use of the menu at all, still something that does slow the user down.
Otherwise, love this! 
Note:

- Only happens in single selection menu
- Only happens when a selection of an item is made
- Double tap to bring the options back up again
- > You do see the arrow flip for each tap
- No big, just a little style issue

https://user-images.githubusercontent.com/19269477/108019967-2e8ff880-6fd0-11eb-801c-d59b757b833f.mov

**Comment by KitsuneNoctus** [comment]
Worked on the source, think I found a solution for the issue. If you don't mind, I would love to submit a pull request for it.

**Comment by KarimEbrahemAbdelaziz** [comment]
Hi @KitsuneNoctus 👋
Thank you for your issue report.
Sure, it would be great if you submit a PR solving this issue, I'll review it ASAP 🔥

**Comment by KarimEbrahemAbdelaziz** [comment]
Fixed. 
Thanks @KitsuneNoctus for your PR.

**Comment by SamH2022** [comment]
Even though `titleForHeaderInSection` is not being called _"@KitsuneNoctus fix"_ , that didn't work for me.
What I found is, `state.toggle()` is not being called from `didSelectRowAt` which changes the state from `shown` to `hidden`, but it's called from `handleMenuState()` that's why it works perfectly fine If I don't select any item from the menu and it requires 2 taps to make it expand again If I select an item.
I don't know If this is intended behaviour or I'm suppose to call `.toggle()` myself, but what works for me is:
`languageDropdownMenu.didSelectItem = { _, item, index in`
            `print("Selected from Code \(item) at index: \(index)")`            
          `self.languageDropdownMenu.toggle()
        }`
